---

name: Action self-test

on:
  - push

jobs:
  test-action:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test the action locally
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: matmar10/sync-labels
